# Config
theme: jekyll-theme-minimal
logo: /images/BrandtsBrewVector.png

# Social stuff
location: Atlanta, GA
twitter_username: rembrandtuuu
github_username: mkopsho
linkedin_username: michael-kopsho
