# Config
theme: jekyll-theme-minimal
logo: /images/me_donut.jpg
title: Michael Kopsho

# Social stuff
location: Atlanta, GA
twitter_username: Michael_Tsunam1
github_username: mkopsho
linkedin_username: michael-kopsho-b2b37a2a
