# Config
theme: slate
title: Copslop
description: Kopsho's site. I post about things that I like.

# Social stuff
location: Atlanta, GA
twitter_username: Michael_Tsunam1
github_username: mkopsho
linkedin_username: michael.kopsho@gmail.com
